repos:
  - repo: local
    rev: v4.3.0
hooks:
  - id: pylint # pylint is a pre-commit hook that runs as a linter to check for style
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=pylintrc", # Link to your config file
        ]
