name: Demo
on:
   pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-workflow1:
    uses: ./.github/workflows/pylint.yaml
  call-workflow2:
    needs: call-workflow1
    uses: ./.github/workflows/pytest.yaml
