name: Demo
on:
   pull_request:
    branches: [main]
   push:
    branches: [main]
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install pre-commit
        run: |
          pip install pre-commit
  pylint:
    uses: ./.github/workflows/pylint.yml
  pytest:
    needs: pylint
    uses: ./.github/workflows/pytest.yml
