name: Python Pytest
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
 pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: Install pre-commit
        run: |
          pip install pre-commit
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest $(git ls-files '*.py')
